#!/bin/bash
# Tor Gateway Setup Script
# Configures Debian VM as Tor transparent proxy gateway
# Run this on the Gateway VM as root or with sudo

set -e

echo "=========================================="
echo "Tor Gateway Configuration Script"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration variables
INTERNAL_IP="10.152.152.10"
INTERNAL_NET="10.152.152.0/24"
INTERNAL_IFACE="eth1"
EXTERNAL_IFACE="eth0"

echo -e "${YELLOW}Step 1: Checking prerequisites...${NC}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}ERROR: Please run as root or with sudo${NC}"
    exit 1
fi

# Verify network interfaces exist
if ! ip link show "$INTERNAL_IFACE" &>/dev/null; then
    echo -e "${RED}ERROR: Internal interface $INTERNAL_IFACE not found${NC}"
    echo "Available interfaces:"
    ip link show
    exit 1
fi

if ! ip link show "$EXTERNAL_IFACE" &>/dev/null; then
    echo -e "${RED}ERROR: External interface $EXTERNAL_IFACE not found${NC}"
    echo "Available interfaces:"
    ip link show
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites OK${NC}"
echo ""

echo -e "${YELLOW}Step 2: Installing Tor and dependencies...${NC}"
apt update
apt install -y tor tor-geoipdb nftables curl dnsutils

echo -e "${GREEN}✓ Packages installed${NC}"
echo ""

echo -e "${YELLOW}Step 3: Configuring Tor...${NC}"

# Backup existing torrc
if [ -f /etc/tor/torrc ]; then
    cp /etc/tor/torrc /etc/tor/torrc.backup.$(date +%Y%m%d-%H%M%S)
    echo "Backed up existing torrc"
fi

# Create new torrc
cat > /etc/tor/torrc << 'EOF'
# Tor Gateway Configuration
# Generated by fix-tor-gateway.sh

# Virtual address network for transparent proxy
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1

# Transparent proxy port - redirects TCP traffic
TransPort 10.152.152.10:9040 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort

# DNS port - handles DNS queries through Tor
DNSPort 10.152.152.10:5353

# SOCKS ports for different isolation streams
SocksPort 10.152.152.10:9050 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort
SocksPort 10.152.152.10:9051 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort
SocksPort 10.152.152.10:9052 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort

# Also listen on localhost for local testing
SocksPort 127.0.0.1:9050

# Logging (can be disabled in production)
Log notice file /var/log/tor/notices.log

# Security
DisableDebuggerAttachment 0
EOF

echo -e "${GREEN}✓ Tor configuration written to /etc/tor/torrc${NC}"
echo ""

echo -e "${YELLOW}Step 4: Setting Tor ownership and permissions...${NC}"
chown -R debian-tor:debian-tor /var/lib/tor
chmod 700 /var/lib/tor
mkdir -p /var/log/tor
chown debian-tor:debian-tor /var/log/tor

echo -e "${GREEN}✓ Permissions set${NC}"
echo ""

echo -e "${YELLOW}Step 5: Enabling IP forwarding...${NC}"

# Enable IP forwarding
if ! grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.conf; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi

sysctl -w net.ipv4.ip_forward=1

echo -e "${GREEN}✓ IP forwarding enabled${NC}"
echo ""

echo -e "${YELLOW}Step 6: Configuring firewall (nftables)...${NC}"

# Create nftables configuration
cat > /etc/nftables.conf << 'EOF'
#!/usr/sbin/nft -f

# Tor Gateway Firewall Rules
# CRITICAL: Only allows Tor user to reach internet

flush ruleset

define INTERNAL_NET = 10.152.152.0/24
define GATEWAY_IP = 10.152.152.10

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        
        # Allow loopback
        iif lo accept
        
        # Allow established/related connections
        ct state established,related accept
        
        # Allow SSH from internal network (management)
        iif eth1 ip saddr $INTERNAL_NET tcp dport 22 accept
        
        # Allow Tor ports from internal network
        iif eth1 ip saddr $INTERNAL_NET tcp dport {9040, 9050, 9051, 9052} accept
        iif eth1 ip saddr $INTERNAL_NET udp dport 5353 accept
        
        # Allow ICMP for diagnostics
        ip protocol icmp accept
    }
    
    chain forward {
        type filter hook forward priority 0; policy drop;
        
        # Allow established/related
        ct state established,related accept
        
        # Forward from internal network
        iif eth1 ip saddr $INTERNAL_NET accept
    }
    
    chain output {
        type filter hook output priority 0; policy drop;
        
        # Allow loopback
        oif lo accept
        
        # Allow established/related
        ct state established,related accept
        
        # CRITICAL: Only Tor user can reach internet via eth0
        oif eth0 skuid debian-tor accept
        
        # Allow all output to internal network
        oif eth1 accept
        
        # Allow ICMP
        ip protocol icmp accept
    }
}

table ip nat {
    chain prerouting {
        type nat hook prerouting priority -100; policy accept;
        
        # Redirect DNS queries to Tor DNSPort
        iif eth1 ip saddr $INTERNAL_NET udp dport 53 redirect to :5353
        
        # Redirect HTTP/HTTPS to Tor TransPort
        iif eth1 ip saddr $INTERNAL_NET tcp dport {80, 443} redirect to :9040
        
        # Redirect all other TCP to Tor TransPort
        iif eth1 ip saddr $INTERNAL_NET tcp flags syn redirect to :9040
    }
    
    chain postrouting {
        type nat hook postrouting priority 100; policy accept;
        
        # Masquerade traffic going to internet
        oif eth0 masquerade
    }
}
EOF

echo -e "${GREEN}✓ Firewall rules written to /etc/nftables.conf${NC}"
echo ""

echo -e "${YELLOW}Step 7: Starting services...${NC}"

# Start and enable Tor
systemctl enable tor
systemctl restart tor

echo "Waiting for Tor to bootstrap..."
sleep 5

# Check Tor status
if systemctl is-active --quiet tor; then
    echo -e "${GREEN}✓ Tor is running${NC}"
else
    echo -e "${RED}✗ Tor failed to start${NC}"
    echo "Check logs: journalctl -u tor -n 50"
    exit 1
fi

# Load firewall rules
systemctl enable nftables
systemctl restart nftables

if systemctl is-active --quiet nftables; then
    echo -e "${GREEN}✓ Firewall is active${NC}"
else
    echo -e "${RED}✗ Firewall failed to start${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}Step 8: Running diagnostics...${NC}"
echo ""

# Wait a bit more for Tor to fully bootstrap
echo "Waiting 10 seconds for Tor to fully bootstrap..."
sleep 10

echo "=== Network Interfaces ==="
ip addr show "$INTERNAL_IFACE" | grep "inet "
echo ""

echo "=== Tor Listening Ports ==="
ss -tlnp | grep tor || echo "No TCP ports found"
ss -unlp | grep tor || echo "No UDP ports found"
echo ""

echo "=== IP Forwarding ==="
sysctl net.ipv4.ip_forward
echo ""

echo "=== Tor Circuit Status ==="
journalctl -u tor --no-pager | grep -i "bootstrapped" | tail -1
echo ""

echo "=== Testing Tor (via localhost SOCKS) ==="
timeout 10 curl --socks5-hostname 127.0.0.1:9050 https://check.torproject.org/api/ip 2>/dev/null || echo "SOCKS test failed - Tor may still be bootstrapping"
echo ""

echo "=========================================="
echo -e "${GREEN}Configuration Complete!${NC}"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Check Tor bootstrap status: journalctl -u tor -f"
echo "   (Wait for 'Bootstrapped 100% (done)')"
echo ""
echo "2. Test from this Gateway VM:"
echo "   curl --socks5-hostname 127.0.0.1:9050 https://ifconfig.me"
echo "   (Should show Tor exit IP, NOT your home IP)"
echo ""
echo "3. Test from Workstation VM:"
echo "   curl https://ifconfig.me"
echo "   (Should show Tor exit IP)"
echo ""
echo "4. Verify Tor status:"
echo "   curl https://check.torproject.org/api/ip"
echo '   (Should return {"IsTor":true,...})'
echo ""
echo -e "${YELLOW}IMPORTANT: If tests fail, check logs with:${NC}"
echo "   journalctl -u tor -n 100"
echo "   nft list ruleset"
echo ""
