#!/bin/bash
# Automated Tide Gateway Build for UTM

echo "🚀 Building Tide Gateway in UTM..."
echo ""
echo "⚠️  MANUAL STEPS REQUIRED (UTM CLI doesn't support VM creation)"
echo ""
echo "Please do this in UTM app:"
echo ""
echo "1. Open UTM"
echo "2. Click '+' → Virtualize"
echo "3. Select 'Linux'"
echo "4. Browse to: $(pwd)/nocloud_alpine-3.19.6-aarch64-uefi-tiny-r0.qcow2"
echo "5. Memory: 512 MB, CPU: 1 core"
echo "6. Name: Tide-Gateway"
echo "7. BEFORE starting:"
echo "   - Right-click VM → Edit"
echo "   - Add CD/DVD → $(pwd)/cloud-init.iso"
echo "   - Network → Add adapter → Host Only"
echo "   - Save"
echo "8. Start VM and wait 2-3 minutes"
echo "9. Test: ssh alpine@10.101.101.10 (password: tide)"
echo ""
echo "Files ready at: $(pwd)"
echo "- nocloud_alpine-3.19.6-aarch64-uefi-tiny-r0.qcow2 (boot disk)"
echo "- cloud-init.iso (auto-configuration)"
echo ""
echo "Gateway IP: 10.101.101.10"
echo "Network: 10.101.101.0/24 (supports multiple client VMs)"
